spring:
  datasource:
    username: root
    password: mysql.mylove
    url: jdbc:mysql://124.70.58.37:3306/gulimall_pms?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
mybatis-plus:
  mapper-location: classpath*:/mapper/**/*.xml  #
  global-config:
    db-config:
#      设置主键自增
      id-type: auto
server:
  port: 10000