spring:
  datasource:
    username: root
    password: mysql.mylove
    url: jdbc:mysql://124.70.58.37:3306/gulimall_wms?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-location: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      #      设置主键自增
      id-type: auto
server:
  port: 11000